---
- hosts: all
  tasks:
  - name: Install Jenkins
    apt: name=jenkins update_cache=yes
    sudo: true
  - name: Jenkins Job Path
    file: path=/var/lib/jenkins/jobs/install_lighttpd state=directory owner=jenkins group=jenkins mode=0755
    sudo: true
  - name: Jenkins Job File
    copy: src=./mytemplates/config.xml dest=/var/lib/jenkins/jobs/install_lighttpd/config.xml owner=jenkins group=jenkins mode=0644
    sudo: true
    register: config_update
  - name: Restarting Jenkins to Pull in Config File
    command: service jenkins restart
    sudo: true
    when: config_update.changed
  - name: Install Lighttpd Dependancies
    apt: name=make,libpcre3-dev,libbz2-dev update_cache=yes
    sudo: true
  - name: Install Jenkins CLI Tool
    copy: src=./mytemplates/jenkins-cli.jar dest=/home/vagrant/jenkins-cli.jar mode=0665
  - name: Sleeping After Jenkins Restart
    command: sleep 10
    register: jenkins_sleep
    when: config_update.changed
  - name: Start Jenkins Job
    command: java -jar jenkins-cli.jar -s http://192.168.111.222:8080/ build install_lighttpd
    sudo: true
    when: jenkins_sleep.changed
